heat_template_version: 2013-05-23

description: >
  Simple template to deploy a single compute instance

parameters:
  image:
    type: string
    description: Image ID or image name to use for the server
    constraints:
      - custom_constraint: glance.image
  flavor:
    type: string
    description: Flavor for the server to be created
    default: m1.small
    constraints:
      - custom_constraint: nova.flavor
  flavor_update:
    type: string
    description: Flavor update policy
    default: "RESIZE"
  network:
    type: string
    description: Network used by the server 
  admin_pass:
    type: string
    description: Admin password
    hidden: true
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
  user_data:
    type: string
    description: Server user_data
  metadata:
    type: json
    description: Server meta_data
  pool_id:
    type: string
    description: Pool to contact
  security_group:
    type: string
    default: "default"
    description: SG for the server
  port_number:
    type: number
    default: 80
    description: Port number to be configured for the server
  weight:
    type: number
    default: 1
    description: Weight to be configured for the server
    
resources:
  wserver:
    type: OS::Nova::Server
    properties:
      config_drive: "true"
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks: [ {network: {get_param: network} }]
      admin_pass: { get_param: admin_pass }
      key_name: {get_param: key_name}
      user_data: {get_param: user_data}
      user_data_format: RAW
      metadata: {get_param: metadata}
      security_groups: [{ get_param: security_group }]
      flavor_update_policy: { get_param: flavor_update }

  member:
    type: OS::Neutron::PoolMember
    depends_on: wserver
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [wserver, first_address]}
      protocol_port: {get_param: port_number}
      weight: {get_param: weight}

outputs:
  details:
    value: { get_attr: [wserver, show] }

#heat stack-create -f lb.yaml lb -P image=www-nginx -P flavor=m1.small -P network=avi-mgmt -P admin_pass=blah -P security_group="844f5b1b-55c1-46ed-bab5-21e527da82e2" -P key_name=heat_key -P pool_id=4f5590d9-5b72-421d-92bc-0a64f71feaf4 -P metadata='{"name":"siva","test":"heat trials"}' -P user_data="user=root;data=blah"